### PR TITLE
Fix grammar errors, and change word choice

### PR DESCRIPTION
**Pull request by jdev082**
Basically, swaps or removes some words. Overall improving the guidelines. If you don't agree with a grammar change just let me know. Also, sometimes some words just aren't needed. And adding them can make the sentences less fluid. This PR also removes confusing remarks.

### CODE REVIEW

**Comment by jdev082** [comment]
This PR is currently undergoing testing.

**Comment by jdev082** [comment]
Works

**Comment by MystPi** [comment]
I already changed a few of those in an earlier commit. Try pulling the latest changes.

**Comment by MystPi** [comment]
Thanks for contributing!

**Pull request merged**
